### ISSUE TITLE
Upload to hackage

### ISSUE THREAD

**Issue by fshp** [hackage-trustees/regex-tdfa-text#1]

**Comment by bergmark** [comment]
I hope it can be done soon, I'm waiting for another trustee to review haskell-infra/hackage-trustees#40

**Comment by fshp** [comment]
Maybe better use this [repo](https://github.com/factisresearch/regex-tdfa-text)? He saved old history from original darcs repo.

**Comment by bergmark** [comment]
This is just a temporary place for this fix, it will be removed afterwards.

**Comment by bergmark** [comment]
Uploaded http://hackage.haskell.org/package/regex-tdfa-text-1.0.0.3
